import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/config/globals.css";
import { cn } from "@/lib/utils";
import Header from "@/layouts/Header";
import Footer from "@/layouts/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="h-full scroll-m-20 scroll-smooth"
      suppressHydrationWarning
    >
      <body className={cn(inter.className, "flex min-h-screen flex-col")}>
        <>
          <Header />
          <main className="mt-[64px] flex flex-1 flex-col">{children}</main>
          <Footer />
        </>
      </body>
    </html>
  );
}
